# Generated by Django 4.0.4 on 2022-10-20 16:41
from django.contrib.auth import get_user_model
from django.db import migrations
import os


def create_superuser(apps, schema_editor):
    User = get_user_model()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
