services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/.env
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - backend_network
      - db_network
    volumes:
      - .:/app
  db:
    image: postgres:14-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - ./env/.env
    ports:
      - 5432:5432
    networks:
      - db_network
volumes:
  db_volume:

networks:
  backend_network:
    driver: bridge
  db_network:
    driver: bridge
