# Generated by Django 4.1.2 on 2022-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
