# Generated by Django 4.1.2 on 2022-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
